### PR TITLE
1.21 Port

### PR DESCRIPTION
**Pull request by Sollace**
Updated and tested with 1.21 as best as I could. ~~I don't expect this to become to be released officially (maybe publish it as a -beta version) as we still need to wait on EMI to sort out their things, but I figure having Tla working now will help a lot for developers who need it before they start their own porting work.~~

## Notes

~~1. Since EMI hasn't yet released a version, I've used a build based on the currently-active 1.21 PR at https://github.com/emilyploszaj/emi/pull/558. As such, I'd had to add a /lib folder with the build artefacts that you'll likely want to swap out for the repo version once EMI has an official release.~~

~~2. I tested it and it appears to be working with EMI. Note to get around a bug in EMI you have to set "use-batched-renderer: false;" in the config otherwise it will crash when redrawing. Enchantments in EMI are also currently broken.~~

\3. I wasn't able to test REI unfortunately, though that does have a proper release so I expect it to be okay. It's just a bit weird to run in my IDE since the compile/runtime sourcesets are merged to I end up with emi, emi's api, and rei all together in the same client if I don't manually exclude them. 

## Version Changes

java `17` -> `21`
fabric-api `0.97.8+1.20.6` -> `0.100.1+1.21`

rei `15.0.728` -> `16.0.729`
emi-fabric `1.1.6+1.20.6` -> emi `1.1.7+1.21`

architectury `12.0.26` -> `13.0.1`
cloth-config `14.0.126` -> `15.0.127`

## Screenshot
image

The only thing that seems weird to me in that screenshot is the dirt texture behind the top arrow. Not sure if that's intended to be there or not.

### CODE REVIEW

**Comment by MimzyFang** [comment]
EMI has been updated 
https://github.com/emilyploszaj/emi/tree/1.1.7%2B1.21
https://modrinth.com/mod/emi/version/1.1.7+1.21+fabric

@Sollace the merge request you used has not been used for the update so you might need to change things

**Comment by Sollace** [comment]
> EMI has been updated https://github.com/emilyploszaj/emi/tree/1.1.7%2B1.21 https://modrinth.com/mod/emi/version/1.1.7+1.21+fabric
> 
> @Sollace the merge request you used has not been used for the update so you might need to change things

Yeah, I saw last night. I planned already to update the PR after I saw they did a branch. Now there's a release it makes things even easier.

**Comment by Sollace** [comment]
Updates are done. Now using the official release of EMI, and minecraft 1.21 instead of 1.21-rc.1 (I'll just bump my min version in my own projects).

**Comment by Sollace** [comment]
@MattiDragon Added a fix for #4 . You don't need to explicitly include the sources. It's added with the component by default when you specify `withSourcesJar()`

**Review by MattiDragon — APPROVED** [review]
Seems to be mostly good. Only thing more I'd want is an update to loom 1.7, but I can do that myself.

**Pull request merged**
